---
title: "Lab 00 - Hello IDS!"
author: "Akshit Wadhawan"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Akshit","Akki", "John", "Steve"),
  github_username = c("akshitwadhawan","blemishcontrolfreak", "john-heywood290", "stavros-michail"),
  colour = c("blue","blue", "blue", "blue"
             ),
  hobby = c("Gaming", "Rock Climbing", "Football", 
            "Scrolling on Social Media"),
  favourite_number = c(7 ,7 ,1 ,4 )
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```


*Remove this text (including the stars), and add your answer for Exercise 18 here.*

### Exercises 19

Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "GitHub Username", 
          y = "Favourite Number 1-10",
          title = "Github Username Vs. Favourite Number")
```

Modify axis, legend, and plot labels

### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```

A Pie Chart
